server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8003/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eurekaservice
